name: Simple Mailer Service

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Deploy to Heroku
        run:
          - ./ci/deploy.sh ${{ secrets.HEROKU_APP }}
